### ISSUE TITLE
is this available?

### ISSUE THREAD

**Issue by babakmdi** [ketanjawahire/TikTok.ApiClient#9]

**Comment by ketanjawahire** [comment]
Hey @babakmdi, 
Thank you for showing interest in my project. 

It is currently under development. You can check current progress under develop branch. 
Unfortunately I haven't been able to add much documentation. I'm posting sample code which should give you enough idea on how to use it(if you decide to use it).

```c-sharp
var apiClient = new TikTokServices("accessToken");

var campaignService = apiClient.GetService<ICampaignService>();

var requestModel = new TikTok.ApiClient.Entities.CampaignRequestModel() {
    AdvertiserId = 123,
    Filtering = new TikTok.ApiClient.Entities.CampaignRequestFilter() {
        CampaignName = "CampaignName"
    }
};

var result = await campaignService.Get(requestModel);
```

Nuget pakage - [https://www.nuget.org/packages/TikTok.ApiClient/](https://www.nuget.org/packages/TikTok.ApiClient/)

**Comment by babakmdi** [comment]
can i get just videos? i want download the videos with the links
